title: "Competency API Developer Docs"
remote-theme: just-the-docs/just-the-docs

# uncomment below for local development, don't forget to re-comment it out
# when you push ur PR or you will feel like a silly billy
# theme: just-the-docs
